import { parse, Visitor, type Message, type VariableReference } from '@fluent/syntax';

/**
 * FTL AST Key & Variable Extractor for TypeScript declaration generation.
 */

export interface ExtractedMessage {
  id: string;
  dotId: string;
  attributes: string[];
  variables: string[];
  valueVariables: string[];
  attributeVariables: Record<string, string[]>;
}

class VariableExtractor extends Visitor {
  public variables = new Set<string>();

  visitVariableReference(node: VariableReference): void {
    if (node.id?.name) {
      this.variables.add(node.id.name);
    }
    this.genericVisit(node);
  }
}

export function extractMessagesFromFtl(ftlContent: string): ExtractedMessage[] {
  const resource = parse(ftlContent, { withSpans: false });
  const messages: ExtractedMessage[] = [];

  for (const entry of resource.body) {
    if (entry.type === 'Message') {
      const msg = entry as Message;
      const id = msg.id.name;
      const dotId = id.replace(/-/g, '.');

      const extractor = new VariableExtractor();
      extractor.visit(msg);
      const valueExtractor = new VariableExtractor();
      if (msg.value) valueExtractor.visit(msg.value);

      const attributes: string[] = [];
      const attributeVariables: Record<string, string[]> = {};
      if (msg.attributes) {
        for (const attr of msg.attributes) {
          attributes.push(attr.id.name);
          const attrExtractor = new VariableExtractor();
          attrExtractor.visit(attr.value);
          attributeVariables[attr.id.name] = Array.from(attrExtractor.variables).sort();
        }
      }

      messages.push({
        id,
        dotId,
        attributes,
        variables: Array.from(extractor.variables).sort(),
        valueVariables: Array.from(valueExtractor.variables).sort(),
        attributeVariables,
      });
    }
  }

  return messages;
}

export function generateTypeDeclarations(
  ftlContents: string | readonly string[]
): string {
  const contents = Array.isArray(ftlContents) ? ftlContents : [ftlContents];
  const allMessages: ExtractedMessage[] = [];
  const seenIds = new Set<string>();

  for (const content of contents) {
    const extracted = extractMessagesFromFtl(content);
    for (const msg of extracted) {
      if (seenIds.has(msg.id)) {
        // Last definition wins, matching runtime allowOverrides semantics
        const idx = allMessages.findIndex((m) => m.id === msg.id);
        if (idx !== -1) {
          allMessages[idx] = msg;
        }
      } else {
        seenIds.add(msg.id);
        allMessages.push(msg);
      }
    }
  }

  allMessages.sort((a, b) => a.id.localeCompare(b.id));

  const allKeyEntries: { key: string; variables: string[] }[] = [];
  const seenKeys = new Set<string>();

  const addKeyEntry = (key: string, variables: string[]) => {
    if (!seenKeys.has(key)) {
      seenKeys.add(key);
      allKeyEntries.push({ key, variables });
    }
  };

  for (const m of allMessages) {
    addKeyEntry(m.id, m.valueVariables);
    if (m.dotId !== m.id) {
      addKeyEntry(m.dotId, m.valueVariables);
    }
    if (m.attributes) {
      for (const attr of m.attributes) {
        const variables = m.attributeVariables[attr] ?? [];
        addKeyEntry(`${m.id}.${attr}`, variables);
        if (m.dotId !== m.id) {
          addKeyEntry(`${m.dotId}.${attr}`, variables);
        }
      }
    }
  }

  const keyUnion = allKeyEntries.map((e) => `  | '${e.key}'`).join('\n');

  const argsEntries = allKeyEntries.map((e) => {
    if (e.variables.length === 0) {
      return `  '${e.key}'?: Record<string, never>;`;
    }
    const varsType = e.variables
      .map((v) => `'${v}': string | number | Date`)
      .join('; ');
    return `  '${e.key}': { ${varsType} };`;
  });

  return `// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
${keyUnion || '  | string'};

export interface AppMessageArgs {
${argsEntries.join('\n')}
}

export interface AppMessages {
${allKeyEntries
  .map((e) => {
    const varsType =
      e.variables.length === 0
        ? 'Record<string, never>'
        : `{ ${e.variables.map((v) => `'${v}': string | number | Date`).join('; ')} }`;
    return `  '${e.key}': ${varsType};`;
  })
  .join('\n')}
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface FluentMessages extends AppMessages {}
}
`;
}
