import { parse, Visitor, type Message, type VariableReference } from '@fluent/syntax';

/**
 * FTL AST Key & Variable Extractor for TypeScript declaration generation.
 */

export interface ExtractedMessage {
  id: string;
  dotId: string;
  attributes: string[];
  variables: string[];
}

class VariableExtractor extends Visitor {
  public variables = new Set<string>();

  visitVariableReference(node: VariableReference): void {
    if (node.id?.name) {
      this.variables.add(node.id.name);
    }
    this.genericVisit(node);
  }
}

export function extractMessagesFromFtl(ftlContent: string): ExtractedMessage[] {
  const resource = parse(ftlContent, { withSpans: false });
  const messages: ExtractedMessage[] = [];

  for (const entry of resource.body) {
    if (entry.type === 'Message') {
      const msg = entry as Message;
      const id = msg.id.name;
      const dotId = id.replace(/-/g, '.');

      const extractor = new VariableExtractor();
      extractor.visit(msg);

      const attributes: string[] = [];
      if (msg.attributes) {
        for (const attr of msg.attributes) {
          attributes.push(attr.id.name);
        }
      }

      messages.push({
        id,
        dotId,
        attributes,
        variables: Array.from(extractor.variables).sort(),
      });
    }
  }

  return messages;
}

export function generateTypeDeclarations(
  ftlContents: string | readonly string[]
): string {
  const contents = Array.isArray(ftlContents) ? ftlContents : [ftlContents];
  const allMessages: ExtractedMessage[] = [];
  const seenIds = new Set<string>();

  for (const content of contents) {
    const extracted = extractMessagesFromFtl(content);
    for (const msg of extracted) {
      if (seenIds.has(msg.id)) {
        // Last definition wins, matching runtime allowOverrides semantics
        const idx = allMessages.findIndex((m) => m.id === msg.id);
        if (idx !== -1) {
          allMessages[idx] = msg;
        }
      } else {
        seenIds.add(msg.id);
        allMessages.push(msg);
      }
    }
  }

  allMessages.sort((a, b) => a.id.localeCompare(b.id));

  const keyUnion = allMessages
    .flatMap((m) => [`  | '${m.id}'`, `  | '${m.dotId}'`])
    .join('\n');

  const argsEntries = allMessages.map((m) => {
    if (m.variables.length === 0) {
      return `  '${m.dotId}'?: Record<string, never>;\n  '${m.id}'?: Record<string, never>;`;
    }
    const varsType = m.variables
      .map((v) => `'${v}': string | number | Date`)
      .join('; ');
    return `  '${m.dotId}': { ${varsType} };\n  '${m.id}': { ${varsType} };`;
  });

  return `// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
${keyUnion || '  | string'};

export interface AppMessageArgs {
${argsEntries.join('\n')}
}

export interface AppMessages {
${allMessages
  .map((m) => {
    const varsType =
      m.variables.length === 0
        ? 'Record<string, never>'
        : `{ ${m.variables.map((v) => `'${v}': string | number | Date`).join('; ')} }`;
    return `  '${m.dotId}': ${varsType};\n  '${m.id}': ${varsType};`;
  })
  .join('\n')}
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface FluentMessages extends AppMessages {}
}
`;
}
