/**
 * FTL AST Key & Variable Extractor for TypeScript declaration generation.
 */

export interface ExtractedMessage {
  id: string;
  dotId: string;
  attributes: string[];
  variables: string[];
}

function extractVariablesFromLine(line: string): string[] {
  // Strip quoted strings so $foo inside "price is $100" isn't treated as variable
  const lineWithoutStrings = line.replace(/"[^"\\]*(?:\\.[^"\\]*)*"/g, '');
  const matches = lineWithoutStrings.matchAll(/\$([a-zA-Z][a-zA-Z0-9_-]*)/g);
  return Array.from(matches, (m) => m[1]);
}

export function extractMessagesFromFtl(ftlContent: string): ExtractedMessage[] {
  const messages: ExtractedMessage[] = [];
  const lines = ftlContent.split(/\r?\n/);

  let currentMsg: ExtractedMessage | null = null;

  for (const line of lines) {
    // Comment or empty line
    if (line.startsWith('#') || !line.trim()) {
      continue;
    }

    // Message definition: `my-message-id = ...`
    // FTL terms start with `-` (e.g. `-brand-name = ...`) and are not callable
    // messages — they must not appear in generated type declarations.
    const msgMatch = line.match(/^([a-zA-Z][a-zA-Z0-9_-]*)\s*=/);
    if (msgMatch) {
      const id = msgMatch[1];
      const dotId = id.replace(/-/g, '.');
      currentMsg = {
        id,
        dotId,
        attributes: [],
        variables: [],
      };
      messages.push(currentMsg);

      for (const v of extractVariablesFromLine(line)) {
        if (!currentMsg.variables.includes(v)) {
          currentMsg.variables.push(v);
        }
      }
      continue;
    }

    // Attribute definition: `  .label = ...`
    const attrMatch = line.match(/^\s+\.([a-zA-Z][a-zA-Z0-9_-]*)\s*=/);
    if (attrMatch && currentMsg) {
      currentMsg.attributes.push(attrMatch[1]);
      for (const v of extractVariablesFromLine(line)) {
        if (!currentMsg.variables.includes(v)) {
          currentMsg.variables.push(v);
        }
      }
      continue;
    }

    // Continuation line with variables
    if (currentMsg) {
      for (const v of extractVariablesFromLine(line)) {
        if (!currentMsg.variables.includes(v)) {
          currentMsg.variables.push(v);
        }
      }
    }
  }

  return messages;
}

export function generateTypeDeclarations(
  ftlContents: string | readonly string[]
): string {
  const contents = Array.isArray(ftlContents) ? ftlContents : [ftlContents];
  const allMessages: ExtractedMessage[] = [];
  const seenIds = new Set<string>();

  for (const content of contents) {
    const extracted = extractMessagesFromFtl(content);
    for (const msg of extracted) {
      if (seenIds.has(msg.id)) {
        // Last definition wins, matching runtime allowOverrides: true semantics.
        const idx = allMessages.findIndex((m) => m.id === msg.id);
        if (idx !== -1) {
          allMessages[idx] = msg;
        }
      } else {
        seenIds.add(msg.id);
        allMessages.push(msg);
      }
    }
  }

  // Sort messages
  allMessages.sort((a, b) => a.id.localeCompare(b.id));

  const keyUnion = allMessages
    .flatMap((m) => [`  | '${m.id}'`, `  | '${m.dotId}'`])
    .join('\n');

  const argsEntries = allMessages.map((m) => {
    if (m.variables.length === 0) {
      return `  '${m.dotId}'?: Record<string, never>;\n  '${m.id}'?: Record<string, never>;`;
    }
    const varsType = m.variables
      .map((v) => `'${v}': string | number | Date`)
      .join('; ');
    return `  '${m.dotId}': { ${varsType} };\n  '${m.id}': { ${varsType} };`;
  });

  return `// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
${keyUnion || "  | string"};

export interface AppMessageArgs {
${argsEntries.join('\n')}
}
`;
}
