// Auto-generated by next-fluent typegen. DO NOT EDIT DIRECTLY.
/* eslint-disable */

export type AppMessageKey =
  | 'app-hello'
  | 'app.hello'
  | 'app-title'
  | 'app.title';

export interface AppMessageArgs {
  'app-hello': { 'name': string | number | Date };
  'app.hello': { 'name': string | number | Date };
  'app-title'?: Record<string, never>;
  'app.title'?: Record<string, never>;
}

export interface AppMessages {
  'app-hello': { 'name': string | number | Date };
  'app.hello': { 'name': string | number | Date };
  'app-title': Record<string, never>;
  'app.title': Record<string, never>;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface FluentMessages extends AppMessages {}
}
